# Generated by Django 3.2 on 2021-05-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_search_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
